create or replace TRIGGER GAME_IS_PLAYED_TRIGGER
BEFORE INSERT
ON GAME_IS_PLAYED
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  IF :NEW.SCORE <=0 OR :NEW.SCORE is NULL THEN
    SELECT
      0
    INTO
      :NEW.SCORE
    FROM DUAL;
  END IF;
  IF :NEW.ANSWERED_QUESTIONS <=0 OR :NEW.ANSWERED_QUESTIONS is NULL THEN
    SELECT
      0
    INTO
      :NEW.ANSWERED_QUESTIONS
    FROM DUAL;
  END IF;
  IF :NEW.CORRECT_ANSWERS <=0 OR :NEW.CORRECT_ANSWERS is NULL THEN
    SELECT
      0
    INTO
      :NEW.CORRECT_ANSWERS
    FROM DUAL;
  END IF;

END;