/*
Modification_date: 2020/10/08
Creator: Alberto Pascal
Last modified by: Alberto Pascal
Description: User's table to manage player data.

*/

/* Creating the table */

CREATE TABLE GAME_IS_PLAYED (
PERIOD_ID NUMBER(10) NOT NULL, 
PLAYER_ID NUMBER(10) NOT NULL,
SCORE NUMBER(32) NOT NULL, 
ANSWERED_QUESTIONS NUMBER(32) NOT NULL,
CORRECT_ANSWERS NUMBER(32) NOT NULL,

CONSTRAINT PLAYER_PERIOD_CONSTRAINT FOREIGN KEY (PERIOD_ID) REFERENCES GAME_PERIOD(PERIOD_ID),
CONSTRAINT PLAYER_GAME_CONSTRAINT FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(USER_ID)
);
COMMIT;
