/*
Modification_date: 2020/10/08
Creator: Alberto Pascal
Last modified by: Alberto Pascal
Description: User's table to manage player data.

*/

/* Creating the table */

CREATE TABLE GAME_PERIOD (
PERIOD_ID NUMBER(10) NOT NULL, 
TOPIC VARCHAR2(32) NOT NULL, 
QUESTION_TIME NUMBER(32) NOT NULL,
SUBSCRIBABLE NUMBER(1) NOT NULL,
CREATION_TIMESTAMP TIMESTAMP ,
DAYS_REMAINING NUMBER(10) DEFAULT 15,

CONSTRAINT PERIOD_ID_CONSTRAINT PRIMARY KEY (PERIOD_ID)
);

/*Creating a sequence for auto-increment id */
CREATE SEQUENCE GAME_ID_SEQUENCE
START WITH 1
INCREMENT BY 1
CACHE 10;

/*Creating a Trigger*/

CREATE OR REPLACE TRIGGER GAME_TRIGGER
BEFORE INSERT
ON GAME_PERIOD
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  SELECT 
    GAME_ID_SEQUENCE.nextval,
    SYSDATE
  INTO 
    :NEW.PERIOD_ID,
    :NEW.CREATION_TIMESTAMP
  FROM dual;
END;
/

ALTER TRIGGER "GAME_TRIGGER" ENABLE;
COMMIT;
