/*
Modification_date: 2020/10/08
Creator: Alberto Pascal
Last modified by: Alberto Pascal
Description: User's table to manage player data.

*/

/* Creating the table */

CREATE TABLE PLAYER (
USER_ID NUMBER(10) NOT NULL, 
USERNAME VARCHAR2(32) NOT NULL, 
CREATION_TIMESTAMP TIMESTAMP NOT NULL,
HIGHSCORE NUMBER(38) DEFAULT 0,
USER_TYPE varchar2(10) DEFAULT 'PLAYER',
CONSTRAINT USER_KEY PRIMARY KEY (USERNAME)
);

/*Creating a sequence for auto-increment id */
CREATE SEQUENCE PLAYER_ID_SEQUENCE
START WITH 1
INCREMENT BY 1
CACHE 10;

/*Creating a Trigger*/

CREATE OR REPLACE TRIGGER PLAYER_TRIGGER
BEFORE INSERT
ON PLAYER
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  IF :NEW.HIGHSCORE IS NULL OR :NEW.HIGHSCORE < 0 THEN
    SELECT 
      0
    INTO
      :NEW.HIGHSCORE
    FROM DUAL;
  END IF;
  SELECT
    PLAYER_ID_SEQUENCE.nextval,
    SYSDATE
  INTO 
    :NEW.USER_ID,
    :NEW.CREATION_TIMESTAMP
  FROM dual;
END;
/

ALTER TRIGGER "PLAYER_TRIGGER" ENABLE;