/*
Modification_date: 2020/10/08
Creator: Alberto Pascal
Last modified by: Alberto Pascal
Description: User's table to manage player data.

*/

/* Creating the table */

CREATE TABLE QUESTION_IN_PERIOD (
PERIOD_ID NUMBER(10) NOT NULL, 
QUESTION_ID NUMBER(10) NOT NULL,

CONSTRAINT PERIOD_QUESTION_CONSTRAINT FOREIGN KEY (PERIOD_ID) REFERENCES GAME_PERIOD(PERIOD_ID),
CONSTRAINT QUESTION_PERIOD_CONTRAINT FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(QUESTION_ID)
);
COMMIT;
