/*
Modification_date: 2020/10/08
Creator: Alberto Pascal
Last modified by: Alberto Pascal
Description: User's table to manage player data.

*/

/* Creating the table */

CREATE TABLE QUESTION (
QUESTION_ID NUMBER(10) NOT NULL, 
QUESTION VARCHAR(500) NOT NULL,
TOPIC VARCHAR2(20) NOT NULL,
OPTION1 VARCHAR2(50) NOT NULL, 
OPTION2 VARCHAR2(50) NOT NULL,
OPTION3 VARCHAR2(50) NOT NULL,
OPTION4 VARCHAR2(50) NOT NULL,
ANSWER INTEGER NOT NULL,
CONSTRAINT QUESTION_CONSTRAINT PRIMARY KEY (QUESTION_ID)
);

/*Creating a sequence for auto-increment id */
CREATE SEQUENCE QUESTIONS_ID_SEC
START WITH 1
INCREMENT BY 1
CACHE 10;

/*Creating a Trigger*/

CREATE OR REPLACE TRIGGER QUESTION_TRIGGER
BEFORE INSERT
ON QUESTION
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  SELECT 
    QUESTIONS_ID_SEC.nextval
  INTO 
    :NEW.QUESTION_ID
  FROM dual;
END;
/

ALTER TRIGGER "QUESTION_TRIGGER" ENABLE;
COMMIT; 

