/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:76d64236-b1c0-442e-882c-01f77a298fc9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8ugEcyU5f",
    "aws_user_pools_web_client_id": "1k600ijpd8ct2jc5jcibfl1cva",
    "oauth": {}
};


export default awsmobile;
