SELECT * FROM PLAYER;
SELECT * FROM GAME_IS_PLAYED;
SELECT * FROM GAME_PERIOD;

--My seasons table
SELECT GAME_IS_PLAYED.PERIOD_ID, TOPIC, SCORE, GAME_PERIOD.DAYS_REMAINING 
FROM GAME_IS_PLAYED JOIN GAME_PERIOD ON GAME_IS_PLAYED.PERIOD_ID = GAME_PERIOD.PERIOD_ID
WHERE GAME_IS_PLAYED.PLAYER_NAME = 'ROY' AND GAME_PERIOD.DAYS_REMAINING >= 1;

--Suscribe to seasons
SELECT PERIOD_ID, TOPIC, DAYS_REMAINING, CREATION_TIMESTAMP 
FROM GAME_PERIOD WHERE GAME_PERIOD.SUBSCRIBABLE = 1 AND GAME_PERIOD.PERIOD_ID NOT IN (SELECT PERIOD_ID FROM GAME_IS_PLAYED WHERE PLAYER_NAME = 'ROY');

--Season summary
SELECT GAME_IS_PLAYED.PERIOD_ID, TOPIC, GAME_IS_PLAYED.SCORE, GAME_PERIOD.DAYS_REMAINING, GAME_PERIOD.CREATION_TIMESTAMP, GAME_PERIOD.CREATION_TIMESTAMP+GAME_PERIOD.DAYS_REMAINING AS EndDate 
FROM GAME_IS_PLAYED JOIN GAME_PERIOD ON GAME_IS_PLAYED.PERIOD_ID = GAME_PERIOD.PERIOD_ID
WHERE GAME_IS_PLAYED.PLAYER_NAME = 'ROY' AND GAME_PERIOD.DAYS_REMAINING = 0;

