/*
Modification_date: 2020/10/31
Creator: Alberto Pascal
Last modified by: Alberto Pascal
Description: Query to fetch all of the profile's data. Best score, categories, etc..

*/

/* Need to replace the where condition with the corresponding username to look for. */

WITH PLAYER_SCORES AS (
    SELECT
        PL.USERNAME,
        AVG(GP.SCORE) AS AVERAGE_SCORE,
        P.TOPIC
    FROM GAME_IS_PLAYED GP
    JOIN GAME_PERIOD P ON P.PERIOD_ID = GP.PERIOD_ID
    JOIN PLAYER PL ON PL.USERNAME = GP.PLAYER_NAME
    GROUP BY PL.USERNAME, P.TOPIC
)
, IMPORTANT_SCORES AS (
    SELECT 
        MAX(AVERAGE_SCORE) AS BEST_SCORE,
        MIN(AVERAGE_SCORE) AS WORST_SCORE,
        USERNAME
    FROM PLAYER_SCORES
    GROUP BY USERNAME
)
,
BEST_TOPIC AS (
SELECT
    P.TOPIC,
    P.USERNAME
FROM PLAYER_SCORES P

JOIN IMPORTANT_SCORES I ON ((I.BEST_SCORE = P.AVERAGE_SCORE))
)
, WORST_TOPIC AS (
SELECT
    P.TOPIC,
    P.USERNAME
FROM PLAYER_SCORES P

JOIN IMPORTANT_SCORES I ON ((I.WORST_SCORE = P.AVERAGE_SCORE))
)
, TOTAL_GAMES AS (
SELECT
    COUNT(*) AS GAMES, 
    PLAYER_NAME
FROM GAME_IS_PLAYED
GROUP BY PLAYER_NAME
)
SELECT 
    T.GAMES AS TOTAL_GAMES_PLAYED,
    P.HIGHSCORE AS BEST_SCORE, 
    B.TOPIC AS BEST_CATEGORY,
    W.TOPIC AS WORST_CATEGORY
FROM PLAYER P
JOIN TOTAL_GAMES T ON T.PLAYER_NAME = P.USERNAME
JOIN BEST_TOPIC B ON P.USERNAME = B.USERNAME
JOIN WORST_TOPIC W ON W.USERNAME = P.USERNAME

WHERE P.USERNAME = 'ADMIN'
